// ⚠️  Auto-generated by bini-router — do not edit.
import React, { Suspense } from 'react';
import { BrowserRouter, Routes, Route, Outlet } from 'react-router-dom';
import './app/globals.css';

const Layout0 = React.lazy(() => import('@/app/layout'));
const NotFound = React.lazy(() => import('@/app/not-found'));
const Page0 = React.lazy(() => import('@/app/page'));

// ─── Error Boundary ───────────────────────────────────────────────────────────
class ErrorBoundary extends React.Component<
  { children: React.ReactNode },
  { error: Error | null }
> {
  constructor(props: { children: React.ReactNode }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) { return { error }; }
  override render() {
    if (this.state.error) return (
      <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', fontFamily: 'system-ui,sans-serif', padding: '2rem' }}>
        <div style={{ maxWidth: 480, width: '100%', textAlign: 'center' }}>
          <h2 style={{ color: '#e74c3c', marginBottom: '1rem' }}>Something went wrong</h2>
          <pre style={{ background: '#fef2f2', padding: '1rem', borderRadius: '0.5rem', textAlign: 'left', fontSize: '0.8rem', color: '#e74c3c', overflow: 'auto' }}>{this.state.error.toString()}</pre>
          <button onClick={() => this.setState({ error: null })} style={{ marginTop: '1rem', padding: '0.5rem 1.5rem', background: '#00CFFF', color: 'white', border: 'none', borderRadius: '0.5rem', cursor: 'pointer', fontWeight: 600 }}>
            Try again
          </button>
        </div>
      </div>
    );
    return this.props.children;
  }
}

function Spinner() {
  return (
    <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: 32, height: 32, border: '3px solid #eee', borderTop: '3px solid #00CFFF', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} />
      <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
    </div>
  );
}

function TitleSetter({ title }: { title: string }) {
  React.useEffect(() => { document.title = title; }, [title]);
  return null;
}



export default function App() {
  return (
    <BrowserRouter basename={import.meta.env.BASE_URL ?? '/'}>
      <Routes>
        <Route element={<><TitleSetter title="Bini.js App" /><Suspense fallback={<Spinner />}><ErrorBoundary><Layout0><Outlet /></Layout0></ErrorBoundary></Suspense></>}>
          <Route path="/" element={<Suspense fallback={<Spinner />}><ErrorBoundary><Page0 /></ErrorBoundary></Suspense>} />
        </Route>
        <Route path="*" element={<Suspense fallback={<Spinner />}><NotFound /></Suspense>} />
      </Routes>
    </BrowserRouter>
  );
}
