// ⚠️  Auto-generated by bini-router on every build — do not edit.
// Add routes by creating files in src/app/api/ only.
// Generated at: 2026-04-09T19:48:38.255Z

import { Hono } from 'hono';
import { cors } from 'hono/cors';
import _route0 from '../src/app/api/hello';

const app = new Hono();
app.use('/api/*', cors({ origin: '*', allowMethods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS'], allowHeaders: ['Content-Type','Authorization'] }));
app.route('/', _route0);

export const config = { runtime: 'edge' };
export default app.fetch;
